specVersion: 0.2.0
name: barTest
version: 0.0.4
description: >-
  This SubQuery project can be use as a starting point for Moonbeam alpha
  network
repository: 'https://github.com/subquery/moonbeam-alpha-subql-starter'

schema:
  file: ./schema.graphql

network:
  endpoint: 'wss://moonbeam-alpha.api.onfinality.io/public-ws'
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  dictionary: 'https://sz.api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js

dataSources:
  - kind: substrate/FrontierEvm
    startBlock: 1967866
    processor:
      file: "./node_modules/@subql/contract-processors/dist/frontierEvm.js"
      options:
        # Must be a key of assets
        abi: contract
        ## The contract that emitted the event
        address: "0x7b462Fbab7e71Ed12FcE321d15813042e902511F"
    assets:
      contract:
        file: "./contract.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleFrontierEvmEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)
        - handler: handleFrontierEvmCall
          kind: substrate/FrontierEvmCall
          filter:
            ## The function can either be the method fragment or signature
            # function: '0x095ea7b3'
            # function: '0x7ff36ab500000000000000000000000000000000000000000000000000000000'
            # function: approve(address,uint256)
            function: approve(address to,uint256 value)

